### ISSUE TITLE
Ansible gather hardware facts causes hang

### ISSUE THREAD

**Issue by jsbarbergit** [ministryofjustice/hmpps-bootstrap#54]
Seen on MIS db servers with ~36 block devices installed. By default the hourly update_users script will gather all facts, which is not necessary in the scope of that task. We've seen it hang and ignore the default 10s timeout when it runs a sg_iqn query against block devices. The sub process sits in uninterruptable IO Wait state and the ansible parent doesn't timeout. Eventually after ~ 3 days the CPU util taken up by the growing number of spinning ansible process maxes out.
It's unclear what the root cause is as it's not consistent across environments or number of devices.

**Comment by smjmoj** [comment]
Solution resolved issue.
